package net.anthavio.disquo.api.response;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Threads are core discussions on the Disqus network which are represented by the standard Disqus embed.
 * https://help.disqus.com/customer/portal/articles/1131785
 * 
 * @author martin.vanek
 * 
 */
public class DisqusThread implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * The Disqus ID number for the thread which is unique across the entire network
	 */
	private Long id;

	/**
	 * Disqus shortname of the forum. Typically this is expandable using related=forum
	 */
	private Object forum; // Related.forum

	/**
	 * The unique category ID that the thread belongs to.
	 */
	private Object category; // Related.category

	/**
	 * Disqus ID number of the author of the thread. By default this is the primary moderator of the forum. Typically this is expandable using related=author
	 */
	private Object author; // Related.author

	/**
	 * The title of the discussion
	 */
	private String title;

	private String clean_title;

	/**
	 * The timestamp of the thread when it was created in the Disqus system.
	 */
	private Date createdAt;

	/**
	 * The unique identifier values passed by the website to a thread (typically using disqus_identifier)
	 */
	private List<String> identifiers;

	private String ipAddress;

	/**
	 * The number of comments, both parents and replies, within a thread.
	 */
	private Integer posts;

	/**
	 * The number of reactions (tweets) detected for the thread
	 */
	private Integer reactions;

	/**
	 * The score that the authenticated user has given to a particular thread. Typically this is just 0 or 1.
	 */
	private Integer userScore;

	/**
	 * The number of unique likes on a thread. This is represented in the embed as stars.
	 */
	private Integer likes;

	/**
	 * The number of unique dislikes for a thread (currently unused)
	 */
	private Integer dislikes;

	/**
	 * Whether or not the thread allows new comments or not.
	 */
	private Boolean isClosed;

	/**
	 * Whether or not the thread has been deleted (killed) by the forum owner
	 */
	private Boolean isDeleted;

	/**
	 * Whether the user has the ability to moderate the thread. 
	 * Will only return true if request is authenticated and if the user is the author of the thread or moderator of the forum.
	 */
	private Boolean canModerate;

	/**
	 * Whether the user can post comments on the thread. 
	 * Will return true for unauthenticated requests only if guest commenting is enabled for the forum, and the thread isn't closed.
	 */
	private Boolean canPost;

	/**
	 * Whether or not the authenticated user has subscribed to the thread by email.
	 */
	private Boolean userSubscription;

	/**
	 * A link to an RSS feed of the latest comments on the thread
	 */
	private String feed;

	/**
	 * The unique slug associated with the thread. This is auto-generated by Disqus in most cases.
	 */
	private String slug;

	/**
	 * URL of the thread. This must be unique to the forum.
	 */
	private String link;

	/**
	 * The content of the article/post that the discussion is about. This is typically empty unless explicitly set by the website.
	 */
	private String message;

	@Override
	public String toString() {
		return JsonStringBuilder.toString(this);
	}

	@Override
	public int hashCode() {
		return this.id == null ? 0 : this.id.hashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DisqusThread other = (DisqusThread) obj;
		if (this.id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!this.id.equals(other.id)) {
			return false;
		}
		return true;
	}

	public void setInitialValues() {
		setDislikes(0);
		setLikes(0);
		setPosts(0);
		setReactions(0);
		setUserScore(0);

		setCanModerate(true);
		setCanPost(true);
		setIsClosed(false);
		setIsDeleted(false);
		setUserSubscription(true);
	}

	public Boolean getCanModerate() {
		return this.canModerate;
	}

	public void setCanModerate(Boolean canModerate) {
		this.canModerate = canModerate;
	}

	public Boolean getCanPost() {
		return this.canPost;
	}

	public void setCanPost(Boolean canPost) {
		this.canPost = canPost;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Object getForum() {
		return this.forum;
	}

	public void setForum(Object forum) {
		this.forum = forum;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCleanTitle() {
		return clean_title;
	}

	public void setCleanTitle(String clean_title) {
		this.clean_title = clean_title;
	}

	public Object getCategory() {
		return this.category;
	}

	public void setCategory(Object category) {
		this.category = category;
	}

	public Object getAuthor() {
		return this.author;
	}

	public void setAuthor(Object author) {
		this.author = author;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public List<String> getIdentifiers() {
		return this.identifiers;
	}

	public void setIdentifiers(List<String> identifiers) {
		this.identifiers = identifiers;
	}

	public Integer getPosts() {
		return this.posts;
	}

	public void setPosts(Integer posts) {
		this.posts = posts;
	}

	public Integer getReactions() {
		return this.reactions;
	}

	public void setReactions(Integer reactions) {
		this.reactions = reactions;
	}

	public Integer getUserScore() {
		return this.userScore;
	}

	public void setUserScore(Integer userScore) {
		this.userScore = userScore;
	}

	public Integer getLikes() {
		return this.likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	public Integer getDislikes() {
		return this.dislikes;
	}

	public void setDislikes(Integer dislikes) {
		this.dislikes = dislikes;
	}

	public Boolean getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(Boolean isClosed) {
		this.isClosed = isClosed;
	}

	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Boolean getUserSubscription() {
		return this.userSubscription;
	}

	public void setUserSubscription(Boolean userSubscription) {
		this.userSubscription = userSubscription;
	}

	public String getFeed() {
		return this.feed;
	}

	public void setFeed(String feed) {
		this.feed = feed;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
